// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/Word.proto

package tw.dictionary.api.parser.model;

public final class Words {
  private Words() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string word = 1;
    boolean hasWord();
    String getWord();
    
    // repeated .tw.dictionary.api.parser.model.Interpret interprets = 2;
    java.util.List<tw.dictionary.api.parser.model.Words.Interpret> 
        getInterpretsList();
    tw.dictionary.api.parser.model.Words.Interpret getInterprets(int index);
    int getInterpretsCount();
    java.util.List<? extends tw.dictionary.api.parser.model.Words.InterpretOrBuilder> 
        getInterpretsOrBuilderList();
    tw.dictionary.api.parser.model.Words.InterpretOrBuilder getInterpretsOrBuilder(
        int index);
  }
  public static final class Word extends
      com.google.protobuf.GeneratedMessage
      implements WordOrBuilder {
    // Use Word.newBuilder() to construct.
    private Word(Builder builder) {
      super(builder);
    }
    private Word(boolean noInit) {}
    
    private static final Word defaultInstance;
    public static Word getDefaultInstance() {
      return defaultInstance;
    }
    
    public Word getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Word_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Word_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string word = 1;
    public static final int WORD_FIELD_NUMBER = 1;
    private java.lang.Object word_;
    public boolean hasWord() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getWord() {
      java.lang.Object ref = word_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          word_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWordBytes() {
      java.lang.Object ref = word_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        word_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .tw.dictionary.api.parser.model.Interpret interprets = 2;
    public static final int INTERPRETS_FIELD_NUMBER = 2;
    private java.util.List<tw.dictionary.api.parser.model.Words.Interpret> interprets_;
    public java.util.List<tw.dictionary.api.parser.model.Words.Interpret> getInterpretsList() {
      return interprets_;
    }
    public java.util.List<? extends tw.dictionary.api.parser.model.Words.InterpretOrBuilder> 
        getInterpretsOrBuilderList() {
      return interprets_;
    }
    public int getInterpretsCount() {
      return interprets_.size();
    }
    public tw.dictionary.api.parser.model.Words.Interpret getInterprets(int index) {
      return interprets_.get(index);
    }
    public tw.dictionary.api.parser.model.Words.InterpretOrBuilder getInterpretsOrBuilder(
        int index) {
      return interprets_.get(index);
    }
    
    private void initFields() {
      word_ = "";
      interprets_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasWord()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInterpretsCount(); i++) {
        if (!getInterprets(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getWordBytes());
      }
      for (int i = 0; i < interprets_.size(); i++) {
        output.writeMessage(2, interprets_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getWordBytes());
      }
      for (int i = 0; i < interprets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, interprets_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Word parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Word parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Word parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tw.dictionary.api.parser.model.Words.Word prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tw.dictionary.api.parser.model.Words.WordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Word_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Word_fieldAccessorTable;
      }
      
      // Construct using tw.dictionary.api.parser.model.Words.Word.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInterpretsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        word_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (interpretsBuilder_ == null) {
          interprets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          interpretsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tw.dictionary.api.parser.model.Words.Word.getDescriptor();
      }
      
      public tw.dictionary.api.parser.model.Words.Word getDefaultInstanceForType() {
        return tw.dictionary.api.parser.model.Words.Word.getDefaultInstance();
      }
      
      public tw.dictionary.api.parser.model.Words.Word build() {
        tw.dictionary.api.parser.model.Words.Word result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tw.dictionary.api.parser.model.Words.Word buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tw.dictionary.api.parser.model.Words.Word result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tw.dictionary.api.parser.model.Words.Word buildPartial() {
        tw.dictionary.api.parser.model.Words.Word result = new tw.dictionary.api.parser.model.Words.Word(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.word_ = word_;
        if (interpretsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            interprets_ = java.util.Collections.unmodifiableList(interprets_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.interprets_ = interprets_;
        } else {
          result.interprets_ = interpretsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tw.dictionary.api.parser.model.Words.Word) {
          return mergeFrom((tw.dictionary.api.parser.model.Words.Word)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tw.dictionary.api.parser.model.Words.Word other) {
        if (other == tw.dictionary.api.parser.model.Words.Word.getDefaultInstance()) return this;
        if (other.hasWord()) {
          setWord(other.getWord());
        }
        if (interpretsBuilder_ == null) {
          if (!other.interprets_.isEmpty()) {
            if (interprets_.isEmpty()) {
              interprets_ = other.interprets_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInterpretsIsMutable();
              interprets_.addAll(other.interprets_);
            }
            onChanged();
          }
        } else {
          if (!other.interprets_.isEmpty()) {
            if (interpretsBuilder_.isEmpty()) {
              interpretsBuilder_.dispose();
              interpretsBuilder_ = null;
              interprets_ = other.interprets_;
              bitField0_ = (bitField0_ & ~0x00000002);
              interpretsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInterpretsFieldBuilder() : null;
            } else {
              interpretsBuilder_.addAllMessages(other.interprets_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasWord()) {
          
          return false;
        }
        for (int i = 0; i < getInterpretsCount(); i++) {
          if (!getInterprets(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              word_ = input.readBytes();
              break;
            }
            case 18: {
              tw.dictionary.api.parser.model.Words.Interpret.Builder subBuilder = tw.dictionary.api.parser.model.Words.Interpret.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addInterprets(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string word = 1;
      private java.lang.Object word_ = "";
      public boolean hasWord() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getWord() {
        java.lang.Object ref = word_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          word_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWord(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        word_ = value;
        onChanged();
        return this;
      }
      public Builder clearWord() {
        bitField0_ = (bitField0_ & ~0x00000001);
        word_ = getDefaultInstance().getWord();
        onChanged();
        return this;
      }
      void setWord(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        word_ = value;
        onChanged();
      }
      
      // repeated .tw.dictionary.api.parser.model.Interpret interprets = 2;
      private java.util.List<tw.dictionary.api.parser.model.Words.Interpret> interprets_ =
        java.util.Collections.emptyList();
      private void ensureInterpretsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          interprets_ = new java.util.ArrayList<tw.dictionary.api.parser.model.Words.Interpret>(interprets_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          tw.dictionary.api.parser.model.Words.Interpret, tw.dictionary.api.parser.model.Words.Interpret.Builder, tw.dictionary.api.parser.model.Words.InterpretOrBuilder> interpretsBuilder_;
      
      public java.util.List<tw.dictionary.api.parser.model.Words.Interpret> getInterpretsList() {
        if (interpretsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(interprets_);
        } else {
          return interpretsBuilder_.getMessageList();
        }
      }
      public int getInterpretsCount() {
        if (interpretsBuilder_ == null) {
          return interprets_.size();
        } else {
          return interpretsBuilder_.getCount();
        }
      }
      public tw.dictionary.api.parser.model.Words.Interpret getInterprets(int index) {
        if (interpretsBuilder_ == null) {
          return interprets_.get(index);
        } else {
          return interpretsBuilder_.getMessage(index);
        }
      }
      public Builder setInterprets(
          int index, tw.dictionary.api.parser.model.Words.Interpret value) {
        if (interpretsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterpretsIsMutable();
          interprets_.set(index, value);
          onChanged();
        } else {
          interpretsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setInterprets(
          int index, tw.dictionary.api.parser.model.Words.Interpret.Builder builderForValue) {
        if (interpretsBuilder_ == null) {
          ensureInterpretsIsMutable();
          interprets_.set(index, builderForValue.build());
          onChanged();
        } else {
          interpretsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addInterprets(tw.dictionary.api.parser.model.Words.Interpret value) {
        if (interpretsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterpretsIsMutable();
          interprets_.add(value);
          onChanged();
        } else {
          interpretsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addInterprets(
          int index, tw.dictionary.api.parser.model.Words.Interpret value) {
        if (interpretsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInterpretsIsMutable();
          interprets_.add(index, value);
          onChanged();
        } else {
          interpretsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addInterprets(
          tw.dictionary.api.parser.model.Words.Interpret.Builder builderForValue) {
        if (interpretsBuilder_ == null) {
          ensureInterpretsIsMutable();
          interprets_.add(builderForValue.build());
          onChanged();
        } else {
          interpretsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addInterprets(
          int index, tw.dictionary.api.parser.model.Words.Interpret.Builder builderForValue) {
        if (interpretsBuilder_ == null) {
          ensureInterpretsIsMutable();
          interprets_.add(index, builderForValue.build());
          onChanged();
        } else {
          interpretsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllInterprets(
          java.lang.Iterable<? extends tw.dictionary.api.parser.model.Words.Interpret> values) {
        if (interpretsBuilder_ == null) {
          ensureInterpretsIsMutable();
          super.addAll(values, interprets_);
          onChanged();
        } else {
          interpretsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearInterprets() {
        if (interpretsBuilder_ == null) {
          interprets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          interpretsBuilder_.clear();
        }
        return this;
      }
      public Builder removeInterprets(int index) {
        if (interpretsBuilder_ == null) {
          ensureInterpretsIsMutable();
          interprets_.remove(index);
          onChanged();
        } else {
          interpretsBuilder_.remove(index);
        }
        return this;
      }
      public tw.dictionary.api.parser.model.Words.Interpret.Builder getInterpretsBuilder(
          int index) {
        return getInterpretsFieldBuilder().getBuilder(index);
      }
      public tw.dictionary.api.parser.model.Words.InterpretOrBuilder getInterpretsOrBuilder(
          int index) {
        if (interpretsBuilder_ == null) {
          return interprets_.get(index);  } else {
          return interpretsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends tw.dictionary.api.parser.model.Words.InterpretOrBuilder> 
           getInterpretsOrBuilderList() {
        if (interpretsBuilder_ != null) {
          return interpretsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(interprets_);
        }
      }
      public tw.dictionary.api.parser.model.Words.Interpret.Builder addInterpretsBuilder() {
        return getInterpretsFieldBuilder().addBuilder(
            tw.dictionary.api.parser.model.Words.Interpret.getDefaultInstance());
      }
      public tw.dictionary.api.parser.model.Words.Interpret.Builder addInterpretsBuilder(
          int index) {
        return getInterpretsFieldBuilder().addBuilder(
            index, tw.dictionary.api.parser.model.Words.Interpret.getDefaultInstance());
      }
      public java.util.List<tw.dictionary.api.parser.model.Words.Interpret.Builder> 
           getInterpretsBuilderList() {
        return getInterpretsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          tw.dictionary.api.parser.model.Words.Interpret, tw.dictionary.api.parser.model.Words.Interpret.Builder, tw.dictionary.api.parser.model.Words.InterpretOrBuilder> 
          getInterpretsFieldBuilder() {
        if (interpretsBuilder_ == null) {
          interpretsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              tw.dictionary.api.parser.model.Words.Interpret, tw.dictionary.api.parser.model.Words.Interpret.Builder, tw.dictionary.api.parser.model.Words.InterpretOrBuilder>(
                  interprets_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          interprets_ = null;
        }
        return interpretsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tw.dictionary.api.parser.model.Word)
    }
    
    static {
      defaultInstance = new Word(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tw.dictionary.api.parser.model.Word)
  }
  
  public interface InterpretOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string speech = 1;
    boolean hasSpeech();
    String getSpeech();
    
    // repeated .tw.dictionary.api.parser.model.Explain explains = 2;
    java.util.List<tw.dictionary.api.parser.model.Words.Explain> 
        getExplainsList();
    tw.dictionary.api.parser.model.Words.Explain getExplains(int index);
    int getExplainsCount();
    java.util.List<? extends tw.dictionary.api.parser.model.Words.ExplainOrBuilder> 
        getExplainsOrBuilderList();
    tw.dictionary.api.parser.model.Words.ExplainOrBuilder getExplainsOrBuilder(
        int index);
  }
  public static final class Interpret extends
      com.google.protobuf.GeneratedMessage
      implements InterpretOrBuilder {
    // Use Interpret.newBuilder() to construct.
    private Interpret(Builder builder) {
      super(builder);
    }
    private Interpret(boolean noInit) {}
    
    private static final Interpret defaultInstance;
    public static Interpret getDefaultInstance() {
      return defaultInstance;
    }
    
    public Interpret getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Interpret_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Interpret_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string speech = 1;
    public static final int SPEECH_FIELD_NUMBER = 1;
    private java.lang.Object speech_;
    public boolean hasSpeech() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSpeech() {
      java.lang.Object ref = speech_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          speech_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSpeechBytes() {
      java.lang.Object ref = speech_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        speech_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .tw.dictionary.api.parser.model.Explain explains = 2;
    public static final int EXPLAINS_FIELD_NUMBER = 2;
    private java.util.List<tw.dictionary.api.parser.model.Words.Explain> explains_;
    public java.util.List<tw.dictionary.api.parser.model.Words.Explain> getExplainsList() {
      return explains_;
    }
    public java.util.List<? extends tw.dictionary.api.parser.model.Words.ExplainOrBuilder> 
        getExplainsOrBuilderList() {
      return explains_;
    }
    public int getExplainsCount() {
      return explains_.size();
    }
    public tw.dictionary.api.parser.model.Words.Explain getExplains(int index) {
      return explains_.get(index);
    }
    public tw.dictionary.api.parser.model.Words.ExplainOrBuilder getExplainsOrBuilder(
        int index) {
      return explains_.get(index);
    }
    
    private void initFields() {
      speech_ = "";
      explains_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSpeech()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getExplainsCount(); i++) {
        if (!getExplains(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSpeechBytes());
      }
      for (int i = 0; i < explains_.size(); i++) {
        output.writeMessage(2, explains_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSpeechBytes());
      }
      for (int i = 0; i < explains_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, explains_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Interpret parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tw.dictionary.api.parser.model.Words.Interpret prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tw.dictionary.api.parser.model.Words.InterpretOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Interpret_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Interpret_fieldAccessorTable;
      }
      
      // Construct using tw.dictionary.api.parser.model.Words.Interpret.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExplainsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        speech_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (explainsBuilder_ == null) {
          explains_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          explainsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tw.dictionary.api.parser.model.Words.Interpret.getDescriptor();
      }
      
      public tw.dictionary.api.parser.model.Words.Interpret getDefaultInstanceForType() {
        return tw.dictionary.api.parser.model.Words.Interpret.getDefaultInstance();
      }
      
      public tw.dictionary.api.parser.model.Words.Interpret build() {
        tw.dictionary.api.parser.model.Words.Interpret result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tw.dictionary.api.parser.model.Words.Interpret buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tw.dictionary.api.parser.model.Words.Interpret result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tw.dictionary.api.parser.model.Words.Interpret buildPartial() {
        tw.dictionary.api.parser.model.Words.Interpret result = new tw.dictionary.api.parser.model.Words.Interpret(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.speech_ = speech_;
        if (explainsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            explains_ = java.util.Collections.unmodifiableList(explains_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.explains_ = explains_;
        } else {
          result.explains_ = explainsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tw.dictionary.api.parser.model.Words.Interpret) {
          return mergeFrom((tw.dictionary.api.parser.model.Words.Interpret)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tw.dictionary.api.parser.model.Words.Interpret other) {
        if (other == tw.dictionary.api.parser.model.Words.Interpret.getDefaultInstance()) return this;
        if (other.hasSpeech()) {
          setSpeech(other.getSpeech());
        }
        if (explainsBuilder_ == null) {
          if (!other.explains_.isEmpty()) {
            if (explains_.isEmpty()) {
              explains_ = other.explains_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureExplainsIsMutable();
              explains_.addAll(other.explains_);
            }
            onChanged();
          }
        } else {
          if (!other.explains_.isEmpty()) {
            if (explainsBuilder_.isEmpty()) {
              explainsBuilder_.dispose();
              explainsBuilder_ = null;
              explains_ = other.explains_;
              bitField0_ = (bitField0_ & ~0x00000002);
              explainsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExplainsFieldBuilder() : null;
            } else {
              explainsBuilder_.addAllMessages(other.explains_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSpeech()) {
          
          return false;
        }
        for (int i = 0; i < getExplainsCount(); i++) {
          if (!getExplains(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              speech_ = input.readBytes();
              break;
            }
            case 18: {
              tw.dictionary.api.parser.model.Words.Explain.Builder subBuilder = tw.dictionary.api.parser.model.Words.Explain.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addExplains(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string speech = 1;
      private java.lang.Object speech_ = "";
      public boolean hasSpeech() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSpeech() {
        java.lang.Object ref = speech_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          speech_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSpeech(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        speech_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpeech() {
        bitField0_ = (bitField0_ & ~0x00000001);
        speech_ = getDefaultInstance().getSpeech();
        onChanged();
        return this;
      }
      void setSpeech(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        speech_ = value;
        onChanged();
      }
      
      // repeated .tw.dictionary.api.parser.model.Explain explains = 2;
      private java.util.List<tw.dictionary.api.parser.model.Words.Explain> explains_ =
        java.util.Collections.emptyList();
      private void ensureExplainsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          explains_ = new java.util.ArrayList<tw.dictionary.api.parser.model.Words.Explain>(explains_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          tw.dictionary.api.parser.model.Words.Explain, tw.dictionary.api.parser.model.Words.Explain.Builder, tw.dictionary.api.parser.model.Words.ExplainOrBuilder> explainsBuilder_;
      
      public java.util.List<tw.dictionary.api.parser.model.Words.Explain> getExplainsList() {
        if (explainsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(explains_);
        } else {
          return explainsBuilder_.getMessageList();
        }
      }
      public int getExplainsCount() {
        if (explainsBuilder_ == null) {
          return explains_.size();
        } else {
          return explainsBuilder_.getCount();
        }
      }
      public tw.dictionary.api.parser.model.Words.Explain getExplains(int index) {
        if (explainsBuilder_ == null) {
          return explains_.get(index);
        } else {
          return explainsBuilder_.getMessage(index);
        }
      }
      public Builder setExplains(
          int index, tw.dictionary.api.parser.model.Words.Explain value) {
        if (explainsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExplainsIsMutable();
          explains_.set(index, value);
          onChanged();
        } else {
          explainsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setExplains(
          int index, tw.dictionary.api.parser.model.Words.Explain.Builder builderForValue) {
        if (explainsBuilder_ == null) {
          ensureExplainsIsMutable();
          explains_.set(index, builderForValue.build());
          onChanged();
        } else {
          explainsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addExplains(tw.dictionary.api.parser.model.Words.Explain value) {
        if (explainsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExplainsIsMutable();
          explains_.add(value);
          onChanged();
        } else {
          explainsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addExplains(
          int index, tw.dictionary.api.parser.model.Words.Explain value) {
        if (explainsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExplainsIsMutable();
          explains_.add(index, value);
          onChanged();
        } else {
          explainsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addExplains(
          tw.dictionary.api.parser.model.Words.Explain.Builder builderForValue) {
        if (explainsBuilder_ == null) {
          ensureExplainsIsMutable();
          explains_.add(builderForValue.build());
          onChanged();
        } else {
          explainsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addExplains(
          int index, tw.dictionary.api.parser.model.Words.Explain.Builder builderForValue) {
        if (explainsBuilder_ == null) {
          ensureExplainsIsMutable();
          explains_.add(index, builderForValue.build());
          onChanged();
        } else {
          explainsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllExplains(
          java.lang.Iterable<? extends tw.dictionary.api.parser.model.Words.Explain> values) {
        if (explainsBuilder_ == null) {
          ensureExplainsIsMutable();
          super.addAll(values, explains_);
          onChanged();
        } else {
          explainsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearExplains() {
        if (explainsBuilder_ == null) {
          explains_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          explainsBuilder_.clear();
        }
        return this;
      }
      public Builder removeExplains(int index) {
        if (explainsBuilder_ == null) {
          ensureExplainsIsMutable();
          explains_.remove(index);
          onChanged();
        } else {
          explainsBuilder_.remove(index);
        }
        return this;
      }
      public tw.dictionary.api.parser.model.Words.Explain.Builder getExplainsBuilder(
          int index) {
        return getExplainsFieldBuilder().getBuilder(index);
      }
      public tw.dictionary.api.parser.model.Words.ExplainOrBuilder getExplainsOrBuilder(
          int index) {
        if (explainsBuilder_ == null) {
          return explains_.get(index);  } else {
          return explainsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends tw.dictionary.api.parser.model.Words.ExplainOrBuilder> 
           getExplainsOrBuilderList() {
        if (explainsBuilder_ != null) {
          return explainsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(explains_);
        }
      }
      public tw.dictionary.api.parser.model.Words.Explain.Builder addExplainsBuilder() {
        return getExplainsFieldBuilder().addBuilder(
            tw.dictionary.api.parser.model.Words.Explain.getDefaultInstance());
      }
      public tw.dictionary.api.parser.model.Words.Explain.Builder addExplainsBuilder(
          int index) {
        return getExplainsFieldBuilder().addBuilder(
            index, tw.dictionary.api.parser.model.Words.Explain.getDefaultInstance());
      }
      public java.util.List<tw.dictionary.api.parser.model.Words.Explain.Builder> 
           getExplainsBuilderList() {
        return getExplainsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          tw.dictionary.api.parser.model.Words.Explain, tw.dictionary.api.parser.model.Words.Explain.Builder, tw.dictionary.api.parser.model.Words.ExplainOrBuilder> 
          getExplainsFieldBuilder() {
        if (explainsBuilder_ == null) {
          explainsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              tw.dictionary.api.parser.model.Words.Explain, tw.dictionary.api.parser.model.Words.Explain.Builder, tw.dictionary.api.parser.model.Words.ExplainOrBuilder>(
                  explains_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          explains_ = null;
        }
        return explainsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tw.dictionary.api.parser.model.Interpret)
    }
    
    static {
      defaultInstance = new Interpret(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tw.dictionary.api.parser.model.Interpret)
  }
  
  public interface ExplainOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string content = 1;
    boolean hasContent();
    String getContent();
    
    // repeated .tw.dictionary.api.parser.model.Example examples = 2;
    java.util.List<tw.dictionary.api.parser.model.Words.Example> 
        getExamplesList();
    tw.dictionary.api.parser.model.Words.Example getExamples(int index);
    int getExamplesCount();
    java.util.List<? extends tw.dictionary.api.parser.model.Words.ExampleOrBuilder> 
        getExamplesOrBuilderList();
    tw.dictionary.api.parser.model.Words.ExampleOrBuilder getExamplesOrBuilder(
        int index);
  }
  public static final class Explain extends
      com.google.protobuf.GeneratedMessage
      implements ExplainOrBuilder {
    // Use Explain.newBuilder() to construct.
    private Explain(Builder builder) {
      super(builder);
    }
    private Explain(boolean noInit) {}
    
    private static final Explain defaultInstance;
    public static Explain getDefaultInstance() {
      return defaultInstance;
    }
    
    public Explain getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Explain_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Explain_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string content = 1;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .tw.dictionary.api.parser.model.Example examples = 2;
    public static final int EXAMPLES_FIELD_NUMBER = 2;
    private java.util.List<tw.dictionary.api.parser.model.Words.Example> examples_;
    public java.util.List<tw.dictionary.api.parser.model.Words.Example> getExamplesList() {
      return examples_;
    }
    public java.util.List<? extends tw.dictionary.api.parser.model.Words.ExampleOrBuilder> 
        getExamplesOrBuilderList() {
      return examples_;
    }
    public int getExamplesCount() {
      return examples_.size();
    }
    public tw.dictionary.api.parser.model.Words.Example getExamples(int index) {
      return examples_.get(index);
    }
    public tw.dictionary.api.parser.model.Words.ExampleOrBuilder getExamplesOrBuilder(
        int index) {
      return examples_.get(index);
    }
    
    private void initFields() {
      content_ = "";
      examples_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getExamplesCount(); i++) {
        if (!getExamples(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContentBytes());
      }
      for (int i = 0; i < examples_.size(); i++) {
        output.writeMessage(2, examples_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContentBytes());
      }
      for (int i = 0; i < examples_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, examples_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Explain parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tw.dictionary.api.parser.model.Words.Explain prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tw.dictionary.api.parser.model.Words.ExplainOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Explain_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Explain_fieldAccessorTable;
      }
      
      // Construct using tw.dictionary.api.parser.model.Words.Explain.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExamplesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (examplesBuilder_ == null) {
          examples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          examplesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tw.dictionary.api.parser.model.Words.Explain.getDescriptor();
      }
      
      public tw.dictionary.api.parser.model.Words.Explain getDefaultInstanceForType() {
        return tw.dictionary.api.parser.model.Words.Explain.getDefaultInstance();
      }
      
      public tw.dictionary.api.parser.model.Words.Explain build() {
        tw.dictionary.api.parser.model.Words.Explain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tw.dictionary.api.parser.model.Words.Explain buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tw.dictionary.api.parser.model.Words.Explain result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tw.dictionary.api.parser.model.Words.Explain buildPartial() {
        tw.dictionary.api.parser.model.Words.Explain result = new tw.dictionary.api.parser.model.Words.Explain(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        if (examplesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            examples_ = java.util.Collections.unmodifiableList(examples_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.examples_ = examples_;
        } else {
          result.examples_ = examplesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tw.dictionary.api.parser.model.Words.Explain) {
          return mergeFrom((tw.dictionary.api.parser.model.Words.Explain)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tw.dictionary.api.parser.model.Words.Explain other) {
        if (other == tw.dictionary.api.parser.model.Words.Explain.getDefaultInstance()) return this;
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (examplesBuilder_ == null) {
          if (!other.examples_.isEmpty()) {
            if (examples_.isEmpty()) {
              examples_ = other.examples_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureExamplesIsMutable();
              examples_.addAll(other.examples_);
            }
            onChanged();
          }
        } else {
          if (!other.examples_.isEmpty()) {
            if (examplesBuilder_.isEmpty()) {
              examplesBuilder_.dispose();
              examplesBuilder_ = null;
              examples_ = other.examples_;
              bitField0_ = (bitField0_ & ~0x00000002);
              examplesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExamplesFieldBuilder() : null;
            } else {
              examplesBuilder_.addAllMessages(other.examples_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasContent()) {
          
          return false;
        }
        for (int i = 0; i < getExamplesCount(); i++) {
          if (!getExamples(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              content_ = input.readBytes();
              break;
            }
            case 18: {
              tw.dictionary.api.parser.model.Words.Example.Builder subBuilder = tw.dictionary.api.parser.model.Words.Example.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addExamples(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string content = 1;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
      }
      
      // repeated .tw.dictionary.api.parser.model.Example examples = 2;
      private java.util.List<tw.dictionary.api.parser.model.Words.Example> examples_ =
        java.util.Collections.emptyList();
      private void ensureExamplesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          examples_ = new java.util.ArrayList<tw.dictionary.api.parser.model.Words.Example>(examples_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          tw.dictionary.api.parser.model.Words.Example, tw.dictionary.api.parser.model.Words.Example.Builder, tw.dictionary.api.parser.model.Words.ExampleOrBuilder> examplesBuilder_;
      
      public java.util.List<tw.dictionary.api.parser.model.Words.Example> getExamplesList() {
        if (examplesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(examples_);
        } else {
          return examplesBuilder_.getMessageList();
        }
      }
      public int getExamplesCount() {
        if (examplesBuilder_ == null) {
          return examples_.size();
        } else {
          return examplesBuilder_.getCount();
        }
      }
      public tw.dictionary.api.parser.model.Words.Example getExamples(int index) {
        if (examplesBuilder_ == null) {
          return examples_.get(index);
        } else {
          return examplesBuilder_.getMessage(index);
        }
      }
      public Builder setExamples(
          int index, tw.dictionary.api.parser.model.Words.Example value) {
        if (examplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExamplesIsMutable();
          examples_.set(index, value);
          onChanged();
        } else {
          examplesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setExamples(
          int index, tw.dictionary.api.parser.model.Words.Example.Builder builderForValue) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.set(index, builderForValue.build());
          onChanged();
        } else {
          examplesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addExamples(tw.dictionary.api.parser.model.Words.Example value) {
        if (examplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExamplesIsMutable();
          examples_.add(value);
          onChanged();
        } else {
          examplesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addExamples(
          int index, tw.dictionary.api.parser.model.Words.Example value) {
        if (examplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExamplesIsMutable();
          examples_.add(index, value);
          onChanged();
        } else {
          examplesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addExamples(
          tw.dictionary.api.parser.model.Words.Example.Builder builderForValue) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.add(builderForValue.build());
          onChanged();
        } else {
          examplesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addExamples(
          int index, tw.dictionary.api.parser.model.Words.Example.Builder builderForValue) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.add(index, builderForValue.build());
          onChanged();
        } else {
          examplesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllExamples(
          java.lang.Iterable<? extends tw.dictionary.api.parser.model.Words.Example> values) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          super.addAll(values, examples_);
          onChanged();
        } else {
          examplesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearExamples() {
        if (examplesBuilder_ == null) {
          examples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          examplesBuilder_.clear();
        }
        return this;
      }
      public Builder removeExamples(int index) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.remove(index);
          onChanged();
        } else {
          examplesBuilder_.remove(index);
        }
        return this;
      }
      public tw.dictionary.api.parser.model.Words.Example.Builder getExamplesBuilder(
          int index) {
        return getExamplesFieldBuilder().getBuilder(index);
      }
      public tw.dictionary.api.parser.model.Words.ExampleOrBuilder getExamplesOrBuilder(
          int index) {
        if (examplesBuilder_ == null) {
          return examples_.get(index);  } else {
          return examplesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends tw.dictionary.api.parser.model.Words.ExampleOrBuilder> 
           getExamplesOrBuilderList() {
        if (examplesBuilder_ != null) {
          return examplesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(examples_);
        }
      }
      public tw.dictionary.api.parser.model.Words.Example.Builder addExamplesBuilder() {
        return getExamplesFieldBuilder().addBuilder(
            tw.dictionary.api.parser.model.Words.Example.getDefaultInstance());
      }
      public tw.dictionary.api.parser.model.Words.Example.Builder addExamplesBuilder(
          int index) {
        return getExamplesFieldBuilder().addBuilder(
            index, tw.dictionary.api.parser.model.Words.Example.getDefaultInstance());
      }
      public java.util.List<tw.dictionary.api.parser.model.Words.Example.Builder> 
           getExamplesBuilderList() {
        return getExamplesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          tw.dictionary.api.parser.model.Words.Example, tw.dictionary.api.parser.model.Words.Example.Builder, tw.dictionary.api.parser.model.Words.ExampleOrBuilder> 
          getExamplesFieldBuilder() {
        if (examplesBuilder_ == null) {
          examplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              tw.dictionary.api.parser.model.Words.Example, tw.dictionary.api.parser.model.Words.Example.Builder, tw.dictionary.api.parser.model.Words.ExampleOrBuilder>(
                  examples_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          examples_ = null;
        }
        return examplesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tw.dictionary.api.parser.model.Explain)
    }
    
    static {
      defaultInstance = new Explain(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tw.dictionary.api.parser.model.Explain)
  }
  
  public interface ExampleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string content = 1;
    boolean hasContent();
    String getContent();
  }
  public static final class Example extends
      com.google.protobuf.GeneratedMessage
      implements ExampleOrBuilder {
    // Use Example.newBuilder() to construct.
    private Example(Builder builder) {
      super(builder);
    }
    private Example(boolean noInit) {}
    
    private static final Example defaultInstance;
    public static Example getDefaultInstance() {
      return defaultInstance;
    }
    
    public Example getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Example_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Example_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string content = 1;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Example parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Example parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tw.dictionary.api.parser.model.Words.Example parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tw.dictionary.api.parser.model.Words.Example prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tw.dictionary.api.parser.model.Words.ExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Example_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tw.dictionary.api.parser.model.Words.internal_static_tw_dictionary_api_parser_model_Example_fieldAccessorTable;
      }
      
      // Construct using tw.dictionary.api.parser.model.Words.Example.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tw.dictionary.api.parser.model.Words.Example.getDescriptor();
      }
      
      public tw.dictionary.api.parser.model.Words.Example getDefaultInstanceForType() {
        return tw.dictionary.api.parser.model.Words.Example.getDefaultInstance();
      }
      
      public tw.dictionary.api.parser.model.Words.Example build() {
        tw.dictionary.api.parser.model.Words.Example result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tw.dictionary.api.parser.model.Words.Example buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tw.dictionary.api.parser.model.Words.Example result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tw.dictionary.api.parser.model.Words.Example buildPartial() {
        tw.dictionary.api.parser.model.Words.Example result = new tw.dictionary.api.parser.model.Words.Example(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tw.dictionary.api.parser.model.Words.Example) {
          return mergeFrom((tw.dictionary.api.parser.model.Words.Example)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tw.dictionary.api.parser.model.Words.Example other) {
        if (other == tw.dictionary.api.parser.model.Words.Example.getDefaultInstance()) return this;
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              content_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string content = 1;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:tw.dictionary.api.parser.model.Example)
    }
    
    static {
      defaultInstance = new Example(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tw.dictionary.api.parser.model.Example)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tw_dictionary_api_parser_model_Word_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tw_dictionary_api_parser_model_Word_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tw_dictionary_api_parser_model_Interpret_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tw_dictionary_api_parser_model_Interpret_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tw_dictionary_api_parser_model_Explain_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tw_dictionary_api_parser_model_Explain_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tw_dictionary_api_parser_model_Example_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tw_dictionary_api_parser_model_Example_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031main/resources/Word.proto\022\036tw.dictiona" +
      "ry.api.parser.model\"S\n\004Word\022\014\n\004word\030\001 \002(" +
      "\t\022=\n\ninterprets\030\002 \003(\0132).tw.dictionary.ap" +
      "i.parser.model.Interpret\"V\n\tInterpret\022\016\n" +
      "\006speech\030\001 \002(\t\0229\n\010explains\030\002 \003(\0132\'.tw.dic" +
      "tionary.api.parser.model.Explain\"U\n\007Expl" +
      "ain\022\017\n\007content\030\001 \002(\t\0229\n\010examples\030\002 \003(\0132\'" +
      ".tw.dictionary.api.parser.model.Example\"" +
      "\032\n\007Example\022\017\n\007content\030\001 \002(\tB\'\n\036tw.dictio" +
      "nary.api.parser.modelB\005Words"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tw_dictionary_api_parser_model_Word_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tw_dictionary_api_parser_model_Word_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tw_dictionary_api_parser_model_Word_descriptor,
              new java.lang.String[] { "Word", "Interprets", },
              tw.dictionary.api.parser.model.Words.Word.class,
              tw.dictionary.api.parser.model.Words.Word.Builder.class);
          internal_static_tw_dictionary_api_parser_model_Interpret_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tw_dictionary_api_parser_model_Interpret_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tw_dictionary_api_parser_model_Interpret_descriptor,
              new java.lang.String[] { "Speech", "Explains", },
              tw.dictionary.api.parser.model.Words.Interpret.class,
              tw.dictionary.api.parser.model.Words.Interpret.Builder.class);
          internal_static_tw_dictionary_api_parser_model_Explain_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tw_dictionary_api_parser_model_Explain_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tw_dictionary_api_parser_model_Explain_descriptor,
              new java.lang.String[] { "Content", "Examples", },
              tw.dictionary.api.parser.model.Words.Explain.class,
              tw.dictionary.api.parser.model.Words.Explain.Builder.class);
          internal_static_tw_dictionary_api_parser_model_Example_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_tw_dictionary_api_parser_model_Example_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tw_dictionary_api_parser_model_Example_descriptor,
              new java.lang.String[] { "Content", },
              tw.dictionary.api.parser.model.Words.Example.class,
              tw.dictionary.api.parser.model.Words.Example.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
